# Use the official .NET SDK 8.0 image as the base image for building the application
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build

# Set the working directory in the container
WORKDIR /src

# Copy the project file from the CarStockApi folder and restore any dependencies (via NuGet)
COPY CarStockApi/CarStockApi.csproj ./
RUN dotnet restore

# Copy the rest of the application source code from the CarStockApi folder and build it
COPY /CarStockApi ./
RUN dotnet publish -c Release -o /app --no-restore

# Use the official .NET 8.0 runtime image as the base image for the final stage
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final

# Set the working directory in the container
WORKDIR /app

# Copy the published application from the build stage
COPY --from=build /app ./

# Inform Docker that the container listens on port 8080
EXPOSE 8080

# Run the application
ENTRYPOINT ["dotnet", "CarStockApi.dll"]
